/**
 * Vendors the site's webfonts into public/fonts/ and writes a single local
 * stylesheet.
 *
 * Why: index.html previously pulled two external stylesheets (Fontshare and
 * Google Fonts). Each one is render-blocking and costs a DNS lookup, a TLS
 * handshake and a round trip *before* the font files themselves are even
 * requested — then the browser makes a second hop to a different CDN host for
 * the woff2s. On a Nepali mobile connection that is comfortably a second of
 * dead time against Largest Contentful Paint, and it happens on every page.
 *
 * Self-hosting collapses all of it to same-origin requests that the CDN already
 * has warm, and lets us preload the two fonts used above the fold.
 *
 * Run once (or whenever the font selection changes):  node scripts/fetch-fonts.mjs
 *
 * Licensing: Clash Display and Satoshi are distributed by Fontshare (ITF) free
 * for personal and commercial use including self-hosting; JetBrains Mono is
 * SIL Open Font License 1.1. Both permit redistribution with the site.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const OUT_DIR = join(process.cwd(), "public", "fonts");
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const SOURCES = [
  {
    name: "Fontshare (Clash Display + Satoshi)",
    url: "https://api.fontshare.com/v2/css?f[]=clash-display@500,600,700&f[]=satoshi@400,500,700&display=swap",
  },
  {
    name: "Google Fonts (JetBrains Mono)",
    url: "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&display=swap",
  },
];

/** Turn a remote font URL into a stable, readable local filename. */
function localName(family, weight, remoteUrl) {
  const slug = family.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const ext = remoteUrl.split("?")[0].split(".").pop();
  return `${slug}-${weight}.${ext}`;
}

async function fetchText(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res.text();
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const blocks = [];
  let downloaded = 0;

  for (const source of SOURCES) {
    const css = await fetchText(source.url);

    // Split on @font-face so family/weight/src stay associated.
    const faces = css.split("@font-face").slice(1);

    for (const face of faces) {
      const family = face.match(/font-family:\s*['"]([^'"]+)['"]/)?.[1];
      const weight = face.match(/font-weight:\s*(\d+)/)?.[1] ?? "400";
      const style = face.match(/font-style:\s*(\w+)/)?.[1] ?? "normal";
      const unicodeRange = face.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();

      // Prefer woff2 — smallest, and universally supported by anything that
      // matters in 2026. We deliberately drop the woff/ttf fallbacks.
      const woff2 = face.match(/url\(['"]?((?:https?:)?\/\/[^'")]+\.woff2)['"]?\)/)?.[1];
      if (!family || !woff2) continue;

      const absolute = woff2.startsWith("//") ? `https:${woff2}` : woff2;

      // Google Fonts serves one @font-face per unicode subset — latin,
      // latin-ext, greek, cyrillic, vietnamese — all at the same weight. Keep
      // only the base latin subset, identified by its U+0000-00FF range. The
      // site is English-only, so the other subsets are pure download weight,
      // and keeping them all would collide on filename anyway.
      if (unicodeRange && !unicodeRange.includes("U+0000-00FF")) continue;

      const filename = localName(family, weight, absolute);
      const res = await fetch(absolute, { headers: { "User-Agent": UA } });
      if (!res.ok) {
        console.warn(`  ! skipped ${family} ${weight}: ${res.status}`);
        continue;
      }
      await writeFile(join(OUT_DIR, filename), Buffer.from(await res.arrayBuffer()));
      downloaded++;

      blocks.push(
        [
          "@font-face {",
          `  font-family: '${family}';`,
          `  src: url('/fonts/${filename}') format('woff2');`,
          `  font-weight: ${weight};`,
          `  font-style: ${style};`,
          // swap: show fallback text immediately rather than blocking render.
          // This is what keeps the headline paintable before the font arrives.
          "  font-display: swap;",
          unicodeRange ? `  unicode-range: ${unicodeRange};` : null,
          "}",
        ]
          .filter(Boolean)
          .join("\n"),
      );
    }
    console.log(`✓ ${source.name}`);
  }

  const header = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n`;
  await writeFile(join(OUT_DIR, "fonts.css"), header + blocks.join("\n\n") + "\n");

  console.log(`\n${downloaded} font files written to public/fonts/`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
